# Generated by Django 4.2.23 on 2025-07-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sub_title',
            field=models.CharField(default='Kitob haqida', max_length=200),
        ),
    ]
